filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /home/ubuntu/vulnbank-lab/waf-logs/error.log
  tags: ["modsecurity", "waf"]
  multiline.pattern: '^\['
  multiline.negate: true
  multiline.match: after

output.elasticsearch:
  hosts: ["http://localhost:9200"]

setup.kibana:
  host: "http://localhost:5601"
